// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	go_proto "github.com/openeuler/Conch/api/go_proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProcessServiceName is the fully-qualified name of the ProcessService service.
	ProcessServiceName = "pb.ProcessService"
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "pb.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProcessServiceStartProcessProcedure is the fully-qualified name of the ProcessService's
	// StartProcess RPC.
	ProcessServiceStartProcessProcedure = "/pb.ProcessService/StartProcess"
	// ProcessServiceConnectProcedure is the fully-qualified name of the ProcessService's Connect RPC.
	ProcessServiceConnectProcedure = "/pb.ProcessService/Connect"
	// ProcessServiceListProcedure is the fully-qualified name of the ProcessService's List RPC.
	ProcessServiceListProcedure = "/pb.ProcessService/List"
	// ProcessServiceSendSignalProcedure is the fully-qualified name of the ProcessService's SendSignal
	// RPC.
	ProcessServiceSendSignalProcedure = "/pb.ProcessService/SendSignal"
	// FileServicePostFileStreamProcedure is the fully-qualified name of the FileService's
	// PostFileStream RPC.
	FileServicePostFileStreamProcedure = "/pb.FileService/PostFileStream"
	// FileServiceGetFileStreamProcedure is the fully-qualified name of the FileService's GetFileStream
	// RPC.
	FileServiceGetFileStreamProcedure = "/pb.FileService/GetFileStream"
	// FileServiceListFilesProcedure is the fully-qualified name of the FileService's ListFiles RPC.
	FileServiceListFilesProcedure = "/pb.FileService/ListFiles"
	// FileServiceSearchFilesProcedure is the fully-qualified name of the FileService's SearchFiles RPC.
	FileServiceSearchFilesProcedure = "/pb.FileService/SearchFiles"
)

// ProcessServiceClient is a client for the pb.ProcessService service.
type ProcessServiceClient interface {
	StartProcess(context.Context, *connect.Request[go_proto.StartProcessRequest]) (*connect.ServerStreamForClient[go_proto.ProcessEvent], error)
	Connect(context.Context, *connect.Request[go_proto.ConnectProcessRequest]) (*connect.ServerStreamForClient[go_proto.ProcessEvent], error)
	List(context.Context, *connect.Request[go_proto.ListProcessesRequest]) (*connect.Response[go_proto.ListProcessesResponse], error)
	SendSignal(context.Context, *connect.Request[go_proto.SendSignalRequest]) (*connect.Response[go_proto.SendSignalResponse], error)
}

// NewProcessServiceClient constructs a client for the pb.ProcessService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processServiceMethods := go_proto.File_agent_proto.Services().ByName("ProcessService").Methods()
	return &processServiceClient{
		startProcess: connect.NewClient[go_proto.StartProcessRequest, go_proto.ProcessEvent](
			httpClient,
			baseURL+ProcessServiceStartProcessProcedure,
			connect.WithSchema(processServiceMethods.ByName("StartProcess")),
			connect.WithClientOptions(opts...),
		),
		connect: connect.NewClient[go_proto.ConnectProcessRequest, go_proto.ProcessEvent](
			httpClient,
			baseURL+ProcessServiceConnectProcedure,
			connect.WithSchema(processServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[go_proto.ListProcessesRequest, go_proto.ListProcessesResponse](
			httpClient,
			baseURL+ProcessServiceListProcedure,
			connect.WithSchema(processServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		sendSignal: connect.NewClient[go_proto.SendSignalRequest, go_proto.SendSignalResponse](
			httpClient,
			baseURL+ProcessServiceSendSignalProcedure,
			connect.WithSchema(processServiceMethods.ByName("SendSignal")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processServiceClient implements ProcessServiceClient.
type processServiceClient struct {
	startProcess *connect.Client[go_proto.StartProcessRequest, go_proto.ProcessEvent]
	connect      *connect.Client[go_proto.ConnectProcessRequest, go_proto.ProcessEvent]
	list         *connect.Client[go_proto.ListProcessesRequest, go_proto.ListProcessesResponse]
	sendSignal   *connect.Client[go_proto.SendSignalRequest, go_proto.SendSignalResponse]
}

// StartProcess calls pb.ProcessService.StartProcess.
func (c *processServiceClient) StartProcess(ctx context.Context, req *connect.Request[go_proto.StartProcessRequest]) (*connect.ServerStreamForClient[go_proto.ProcessEvent], error) {
	return c.startProcess.CallServerStream(ctx, req)
}

// Connect calls pb.ProcessService.Connect.
func (c *processServiceClient) Connect(ctx context.Context, req *connect.Request[go_proto.ConnectProcessRequest]) (*connect.ServerStreamForClient[go_proto.ProcessEvent], error) {
	return c.connect.CallServerStream(ctx, req)
}

// List calls pb.ProcessService.List.
func (c *processServiceClient) List(ctx context.Context, req *connect.Request[go_proto.ListProcessesRequest]) (*connect.Response[go_proto.ListProcessesResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// SendSignal calls pb.ProcessService.SendSignal.
func (c *processServiceClient) SendSignal(ctx context.Context, req *connect.Request[go_proto.SendSignalRequest]) (*connect.Response[go_proto.SendSignalResponse], error) {
	return c.sendSignal.CallUnary(ctx, req)
}

// ProcessServiceHandler is an implementation of the pb.ProcessService service.
type ProcessServiceHandler interface {
	StartProcess(context.Context, *connect.Request[go_proto.StartProcessRequest], *connect.ServerStream[go_proto.ProcessEvent]) error
	Connect(context.Context, *connect.Request[go_proto.ConnectProcessRequest], *connect.ServerStream[go_proto.ProcessEvent]) error
	List(context.Context, *connect.Request[go_proto.ListProcessesRequest]) (*connect.Response[go_proto.ListProcessesResponse], error)
	SendSignal(context.Context, *connect.Request[go_proto.SendSignalRequest]) (*connect.Response[go_proto.SendSignalResponse], error)
}

// NewProcessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessServiceHandler(svc ProcessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processServiceMethods := go_proto.File_agent_proto.Services().ByName("ProcessService").Methods()
	processServiceStartProcessHandler := connect.NewServerStreamHandler(
		ProcessServiceStartProcessProcedure,
		svc.StartProcess,
		connect.WithSchema(processServiceMethods.ByName("StartProcess")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceConnectHandler := connect.NewServerStreamHandler(
		ProcessServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(processServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceListHandler := connect.NewUnaryHandler(
		ProcessServiceListProcedure,
		svc.List,
		connect.WithSchema(processServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	processServiceSendSignalHandler := connect.NewUnaryHandler(
		ProcessServiceSendSignalProcedure,
		svc.SendSignal,
		connect.WithSchema(processServiceMethods.ByName("SendSignal")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pb.ProcessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessServiceStartProcessProcedure:
			processServiceStartProcessHandler.ServeHTTP(w, r)
		case ProcessServiceConnectProcedure:
			processServiceConnectHandler.ServeHTTP(w, r)
		case ProcessServiceListProcedure:
			processServiceListHandler.ServeHTTP(w, r)
		case ProcessServiceSendSignalProcedure:
			processServiceSendSignalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessServiceHandler struct{}

func (UnimplementedProcessServiceHandler) StartProcess(context.Context, *connect.Request[go_proto.StartProcessRequest], *connect.ServerStream[go_proto.ProcessEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pb.ProcessService.StartProcess is not implemented"))
}

func (UnimplementedProcessServiceHandler) Connect(context.Context, *connect.Request[go_proto.ConnectProcessRequest], *connect.ServerStream[go_proto.ProcessEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pb.ProcessService.Connect is not implemented"))
}

func (UnimplementedProcessServiceHandler) List(context.Context, *connect.Request[go_proto.ListProcessesRequest]) (*connect.Response[go_proto.ListProcessesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.ProcessService.List is not implemented"))
}

func (UnimplementedProcessServiceHandler) SendSignal(context.Context, *connect.Request[go_proto.SendSignalRequest]) (*connect.Response[go_proto.SendSignalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.ProcessService.SendSignal is not implemented"))
}

// FileServiceClient is a client for the pb.FileService service.
type FileServiceClient interface {
	PostFileStream(context.Context) *connect.ClientStreamForClient[go_proto.FileChunk, go_proto.PostFilesResponse]
	GetFileStream(context.Context, *connect.Request[go_proto.GetFileRequest]) (*connect.ServerStreamForClient[go_proto.FileChunk], error)
	ListFiles(context.Context, *connect.Request[go_proto.ListFilesRequest]) (*connect.Response[go_proto.ListFilesResponse], error)
	SearchFiles(context.Context, *connect.Request[go_proto.SearchFilesRequest]) (*connect.Response[go_proto.SearchFilesResponse], error)
}

// NewFileServiceClient constructs a client for the pb.FileService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fileServiceMethods := go_proto.File_agent_proto.Services().ByName("FileService").Methods()
	return &fileServiceClient{
		postFileStream: connect.NewClient[go_proto.FileChunk, go_proto.PostFilesResponse](
			httpClient,
			baseURL+FileServicePostFileStreamProcedure,
			connect.WithSchema(fileServiceMethods.ByName("PostFileStream")),
			connect.WithClientOptions(opts...),
		),
		getFileStream: connect.NewClient[go_proto.GetFileRequest, go_proto.FileChunk](
			httpClient,
			baseURL+FileServiceGetFileStreamProcedure,
			connect.WithSchema(fileServiceMethods.ByName("GetFileStream")),
			connect.WithClientOptions(opts...),
		),
		listFiles: connect.NewClient[go_proto.ListFilesRequest, go_proto.ListFilesResponse](
			httpClient,
			baseURL+FileServiceListFilesProcedure,
			connect.WithSchema(fileServiceMethods.ByName("ListFiles")),
			connect.WithClientOptions(opts...),
		),
		searchFiles: connect.NewClient[go_proto.SearchFilesRequest, go_proto.SearchFilesResponse](
			httpClient,
			baseURL+FileServiceSearchFilesProcedure,
			connect.WithSchema(fileServiceMethods.ByName("SearchFiles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	postFileStream *connect.Client[go_proto.FileChunk, go_proto.PostFilesResponse]
	getFileStream  *connect.Client[go_proto.GetFileRequest, go_proto.FileChunk]
	listFiles      *connect.Client[go_proto.ListFilesRequest, go_proto.ListFilesResponse]
	searchFiles    *connect.Client[go_proto.SearchFilesRequest, go_proto.SearchFilesResponse]
}

// PostFileStream calls pb.FileService.PostFileStream.
func (c *fileServiceClient) PostFileStream(ctx context.Context) *connect.ClientStreamForClient[go_proto.FileChunk, go_proto.PostFilesResponse] {
	return c.postFileStream.CallClientStream(ctx)
}

// GetFileStream calls pb.FileService.GetFileStream.
func (c *fileServiceClient) GetFileStream(ctx context.Context, req *connect.Request[go_proto.GetFileRequest]) (*connect.ServerStreamForClient[go_proto.FileChunk], error) {
	return c.getFileStream.CallServerStream(ctx, req)
}

// ListFiles calls pb.FileService.ListFiles.
func (c *fileServiceClient) ListFiles(ctx context.Context, req *connect.Request[go_proto.ListFilesRequest]) (*connect.Response[go_proto.ListFilesResponse], error) {
	return c.listFiles.CallUnary(ctx, req)
}

// SearchFiles calls pb.FileService.SearchFiles.
func (c *fileServiceClient) SearchFiles(ctx context.Context, req *connect.Request[go_proto.SearchFilesRequest]) (*connect.Response[go_proto.SearchFilesResponse], error) {
	return c.searchFiles.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the pb.FileService service.
type FileServiceHandler interface {
	PostFileStream(context.Context, *connect.ClientStream[go_proto.FileChunk]) (*connect.Response[go_proto.PostFilesResponse], error)
	GetFileStream(context.Context, *connect.Request[go_proto.GetFileRequest], *connect.ServerStream[go_proto.FileChunk]) error
	ListFiles(context.Context, *connect.Request[go_proto.ListFilesRequest]) (*connect.Response[go_proto.ListFilesResponse], error)
	SearchFiles(context.Context, *connect.Request[go_proto.SearchFilesRequest]) (*connect.Response[go_proto.SearchFilesResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceMethods := go_proto.File_agent_proto.Services().ByName("FileService").Methods()
	fileServicePostFileStreamHandler := connect.NewClientStreamHandler(
		FileServicePostFileStreamProcedure,
		svc.PostFileStream,
		connect.WithSchema(fileServiceMethods.ByName("PostFileStream")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetFileStreamHandler := connect.NewServerStreamHandler(
		FileServiceGetFileStreamProcedure,
		svc.GetFileStream,
		connect.WithSchema(fileServiceMethods.ByName("GetFileStream")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceListFilesHandler := connect.NewUnaryHandler(
		FileServiceListFilesProcedure,
		svc.ListFiles,
		connect.WithSchema(fileServiceMethods.ByName("ListFiles")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceSearchFilesHandler := connect.NewUnaryHandler(
		FileServiceSearchFilesProcedure,
		svc.SearchFiles,
		connect.WithSchema(fileServiceMethods.ByName("SearchFiles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pb.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServicePostFileStreamProcedure:
			fileServicePostFileStreamHandler.ServeHTTP(w, r)
		case FileServiceGetFileStreamProcedure:
			fileServiceGetFileStreamHandler.ServeHTTP(w, r)
		case FileServiceListFilesProcedure:
			fileServiceListFilesHandler.ServeHTTP(w, r)
		case FileServiceSearchFilesProcedure:
			fileServiceSearchFilesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) PostFileStream(context.Context, *connect.ClientStream[go_proto.FileChunk]) (*connect.Response[go_proto.PostFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.FileService.PostFileStream is not implemented"))
}

func (UnimplementedFileServiceHandler) GetFileStream(context.Context, *connect.Request[go_proto.GetFileRequest], *connect.ServerStream[go_proto.FileChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pb.FileService.GetFileStream is not implemented"))
}

func (UnimplementedFileServiceHandler) ListFiles(context.Context, *connect.Request[go_proto.ListFilesRequest]) (*connect.Response[go_proto.ListFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.FileService.ListFiles is not implemented"))
}

func (UnimplementedFileServiceHandler) SearchFiles(context.Context, *connect.Request[go_proto.SearchFilesRequest]) (*connect.Response[go_proto.SearchFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pb.FileService.SearchFiles is not implemented"))
}
