# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: agent.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import agent_pb2 as agent__pb2


class ProcessService(Protocol):
    def start_process(self, request: agent__pb2.StartProcessRequest, ctx: RequestContext) -> AsyncIterator[agent__pb2.ProcessEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def connect(self, request: agent__pb2.ConnectProcessRequest, ctx: RequestContext) -> AsyncIterator[agent__pb2.ProcessEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: agent__pb2.ListProcessesRequest, ctx: RequestContext) -> agent__pb2.ListProcessesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def send_signal(self, request: agent__pb2.SendSignalRequest, ctx: RequestContext) -> agent__pb2.SendSignalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProcessServiceASGIApplication(ConnectASGIApplication[ProcessService]):
    def __init__(self, service: ProcessService | AsyncGenerator[ProcessService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/pb.ProcessService/StartProcess": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StartProcess",
                        service_name="pb.ProcessService",
                        input=agent__pb2.StartProcessRequest,
                        output=agent__pb2.ProcessEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_process,
                ),
                "/pb.ProcessService/Connect": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Connect",
                        service_name="pb.ProcessService",
                        input=agent__pb2.ConnectProcessRequest,
                        output=agent__pb2.ProcessEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.connect,
                ),
                "/pb.ProcessService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="pb.ProcessService",
                        input=agent__pb2.ListProcessesRequest,
                        output=agent__pb2.ListProcessesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
                "/pb.ProcessService/SendSignal": Endpoint.unary(
                    method=MethodInfo(
                        name="SendSignal",
                        service_name="pb.ProcessService",
                        input=agent__pb2.SendSignalRequest,
                        output=agent__pb2.SendSignalResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.send_signal,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/pb.ProcessService"


class ProcessServiceClient(ConnectClient):
    def start_process(
        self,
        request: agent__pb2.StartProcessRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[agent__pb2.ProcessEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StartProcess",
                service_name="pb.ProcessService",
                input=agent__pb2.StartProcessRequest,
                output=agent__pb2.ProcessEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def connect(
        self,
        request: agent__pb2.ConnectProcessRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[agent__pb2.ProcessEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Connect",
                service_name="pb.ProcessService",
                input=agent__pb2.ConnectProcessRequest,
                output=agent__pb2.ProcessEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: agent__pb2.ListProcessesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.ListProcessesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="pb.ProcessService",
                input=agent__pb2.ListProcessesRequest,
                output=agent__pb2.ListProcessesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def send_signal(
        self,
        request: agent__pb2.SendSignalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.SendSignalResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendSignal",
                service_name="pb.ProcessService",
                input=agent__pb2.SendSignalRequest,
                output=agent__pb2.SendSignalResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class FileService(Protocol):
    async def post_file_stream(self, request: AsyncIterator[agent__pb2.FileChunk], ctx: RequestContext) -> agent__pb2.PostFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_file_stream(self, request: agent__pb2.GetFileRequest, ctx: RequestContext) -> AsyncIterator[agent__pb2.FileChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_files(self, request: agent__pb2.ListFilesRequest, ctx: RequestContext) -> agent__pb2.ListFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def search_files(self, request: agent__pb2.SearchFilesRequest, ctx: RequestContext) -> agent__pb2.SearchFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FileServiceASGIApplication(ConnectASGIApplication[FileService]):
    def __init__(self, service: FileService | AsyncGenerator[FileService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/pb.FileService/PostFileStream": Endpoint.client_stream(
                    method=MethodInfo(
                        name="PostFileStream",
                        service_name="pb.FileService",
                        input=agent__pb2.FileChunk,
                        output=agent__pb2.PostFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.post_file_stream,
                ),
                "/pb.FileService/GetFileStream": Endpoint.server_stream(
                    method=MethodInfo(
                        name="GetFileStream",
                        service_name="pb.FileService",
                        input=agent__pb2.GetFileRequest,
                        output=agent__pb2.FileChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_file_stream,
                ),
                "/pb.FileService/ListFiles": Endpoint.unary(
                    method=MethodInfo(
                        name="ListFiles",
                        service_name="pb.FileService",
                        input=agent__pb2.ListFilesRequest,
                        output=agent__pb2.ListFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_files,
                ),
                "/pb.FileService/SearchFiles": Endpoint.unary(
                    method=MethodInfo(
                        name="SearchFiles",
                        service_name="pb.FileService",
                        input=agent__pb2.SearchFilesRequest,
                        output=agent__pb2.SearchFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.search_files,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/pb.FileService"


class FileServiceClient(ConnectClient):
    async def post_file_stream(
        self,
        request: AsyncIterator[agent__pb2.FileChunk],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.PostFilesResponse:
        return await self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="PostFileStream",
                service_name="pb.FileService",
                input=agent__pb2.FileChunk,
                output=agent__pb2.PostFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_file_stream(
        self,
        request: agent__pb2.GetFileRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[agent__pb2.FileChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GetFileStream",
                service_name="pb.FileService",
                input=agent__pb2.GetFileRequest,
                output=agent__pb2.FileChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_files(
        self,
        request: agent__pb2.ListFilesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.ListFilesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFiles",
                service_name="pb.FileService",
                input=agent__pb2.ListFilesRequest,
                output=agent__pb2.ListFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def search_files(
        self,
        request: agent__pb2.SearchFilesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.SearchFilesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchFiles",
                service_name="pb.FileService",
                input=agent__pb2.SearchFilesRequest,
                output=agent__pb2.SearchFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProcessServiceSync(Protocol):
    def start_process(self, request: agent__pb2.StartProcessRequest, ctx: RequestContext) -> Iterator[agent__pb2.ProcessEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def connect(self, request: agent__pb2.ConnectProcessRequest, ctx: RequestContext) -> Iterator[agent__pb2.ProcessEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: agent__pb2.ListProcessesRequest, ctx: RequestContext) -> agent__pb2.ListProcessesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def send_signal(self, request: agent__pb2.SendSignalRequest, ctx: RequestContext) -> agent__pb2.SendSignalResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProcessServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProcessServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/pb.ProcessService/StartProcess": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StartProcess",
                        service_name="pb.ProcessService",
                        input=agent__pb2.StartProcessRequest,
                        output=agent__pb2.ProcessEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_process,
                ),
                "/pb.ProcessService/Connect": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Connect",
                        service_name="pb.ProcessService",
                        input=agent__pb2.ConnectProcessRequest,
                        output=agent__pb2.ProcessEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.connect,
                ),
                "/pb.ProcessService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="pb.ProcessService",
                        input=agent__pb2.ListProcessesRequest,
                        output=agent__pb2.ListProcessesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
                "/pb.ProcessService/SendSignal": EndpointSync.unary(
                    method=MethodInfo(
                        name="SendSignal",
                        service_name="pb.ProcessService",
                        input=agent__pb2.SendSignalRequest,
                        output=agent__pb2.SendSignalResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.send_signal,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/pb.ProcessService"


class ProcessServiceClientSync(ConnectClientSync):
    def start_process(
        self,
        request: agent__pb2.StartProcessRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[agent__pb2.ProcessEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StartProcess",
                service_name="pb.ProcessService",
                input=agent__pb2.StartProcessRequest,
                output=agent__pb2.ProcessEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def connect(
        self,
        request: agent__pb2.ConnectProcessRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[agent__pb2.ProcessEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Connect",
                service_name="pb.ProcessService",
                input=agent__pb2.ConnectProcessRequest,
                output=agent__pb2.ProcessEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: agent__pb2.ListProcessesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.ListProcessesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="pb.ProcessService",
                input=agent__pb2.ListProcessesRequest,
                output=agent__pb2.ListProcessesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def send_signal(
        self,
        request: agent__pb2.SendSignalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.SendSignalResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendSignal",
                service_name="pb.ProcessService",
                input=agent__pb2.SendSignalRequest,
                output=agent__pb2.SendSignalResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class FileServiceSync(Protocol):
    def post_file_stream(self, request: Iterator[agent__pb2.FileChunk], ctx: RequestContext) -> agent__pb2.PostFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_file_stream(self, request: agent__pb2.GetFileRequest, ctx: RequestContext) -> Iterator[agent__pb2.FileChunk]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_files(self, request: agent__pb2.ListFilesRequest, ctx: RequestContext) -> agent__pb2.ListFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def search_files(self, request: agent__pb2.SearchFilesRequest, ctx: RequestContext) -> agent__pb2.SearchFilesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FileServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: FileServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/pb.FileService/PostFileStream": EndpointSync.client_stream(
                    method=MethodInfo(
                        name="PostFileStream",
                        service_name="pb.FileService",
                        input=agent__pb2.FileChunk,
                        output=agent__pb2.PostFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.post_file_stream,
                ),
                "/pb.FileService/GetFileStream": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="GetFileStream",
                        service_name="pb.FileService",
                        input=agent__pb2.GetFileRequest,
                        output=agent__pb2.FileChunk,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_file_stream,
                ),
                "/pb.FileService/ListFiles": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListFiles",
                        service_name="pb.FileService",
                        input=agent__pb2.ListFilesRequest,
                        output=agent__pb2.ListFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_files,
                ),
                "/pb.FileService/SearchFiles": EndpointSync.unary(
                    method=MethodInfo(
                        name="SearchFiles",
                        service_name="pb.FileService",
                        input=agent__pb2.SearchFilesRequest,
                        output=agent__pb2.SearchFilesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.search_files,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/pb.FileService"


class FileServiceClientSync(ConnectClientSync):
    def post_file_stream(
        self,
        request: Iterator[agent__pb2.FileChunk],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.PostFilesResponse:
        return self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="PostFileStream",
                service_name="pb.FileService",
                input=agent__pb2.FileChunk,
                output=agent__pb2.PostFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_file_stream(
        self,
        request: agent__pb2.GetFileRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[agent__pb2.FileChunk]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GetFileStream",
                service_name="pb.FileService",
                input=agent__pb2.GetFileRequest,
                output=agent__pb2.FileChunk,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_files(
        self,
        request: agent__pb2.ListFilesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.ListFilesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFiles",
                service_name="pb.FileService",
                input=agent__pb2.ListFilesRequest,
                output=agent__pb2.ListFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def search_files(
        self,
        request: agent__pb2.SearchFilesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__pb2.SearchFilesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SearchFiles",
                service_name="pb.FileService",
                input=agent__pb2.SearchFilesRequest,
                output=agent__pb2.SearchFilesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
